name: py311

channels:
  - conda-forge

dependencies:
  - python=3.11
  - geopandas
  - pandas
  - numpy
  - shapely
  - rasterio
  - xarray
  - rioxarray
  - gdal
  - pyproj
  - matplotlib
  - tqdm
  - joblib
  - fiona
  - openpyxl
  - xlrd
  - jupyterlab
  - pip
  - pip:
      - osm-flex  

